#!/bin/bash
# =============================================================================
# Ensure Base Domain Script
# Usage: ./ensure-base-domain.sh <env>
# =============================================================================

set -uo pipefail

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
CYAN=$'\e[36m'
DIM=$'\e[2m'
NC=$'\e[0m'

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------
ok()     { echo -e "  ${GREEN}✓${NC} $*"; }
warn()   { echo -e "  ${YELLOW}!${NC} $*"; }
info()   { echo -e "  ${DIM}$*${NC}"; }
header() { echo -e "\n${CYAN}[env-init]${NC} $*"; }

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
ENV_NAME="${1:-dev}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_DIR="${ROOT_DIR}/stacks/${ENV_NAME}"
AUTO_TFVARS="${ENV_DIR}/env.auto.tfvars"
ENV_TFVARS_FILE="${ENV_DIR}/env.tfvars"

mkdir -p "${ENV_DIR}"

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
# Read current base_domain from env.auto.tfvars
current=""
if [[ -f "${AUTO_TFVARS}" ]]; then
  current="$(grep -E '^[[:space:]]*base_domain[[:space:]]*=' "${AUTO_TFVARS}" \
    | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/' | tail -n 1 || true)"
fi

# Fallback: check env.tfvars
if [[ -z "${current}" && -f "${ENV_TFVARS_FILE}" ]]; then
  tfv="$(grep -E '^[[:space:]]*base_domain[[:space:]]*=' "${ENV_TFVARS_FILE}" \
    | sed -E 's/.*=[[:space:]]*\"([^\"]+)\".*/\1/' | tail -n 1 || true)"
  [[ -n "${tfv}" ]] && current="${tfv}"
fi

# Check for placeholder values
is_placeholder="false"
case "${current}" in
  ""|"example.com"|"basedomain.net"|"mymeta.net")
    is_placeholder="true"
    ;;
esac

if [[ "${is_placeholder}" == "true" ]]; then
  header "base_domain is not configured"
  info "Example: mycompany.net"
  read -r -p "Enter base_domain: " input
  
  if [[ -z "${input}" ]]; then
    warn "base_domain is required"
    exit 1
  fi

  cat > "${AUTO_TFVARS}" <<EOF
# Auto-generated by scripts/ensure-base-domain.sh
base_domain = "${input}"
EOF
  ok "Wrote ${AUTO_TFVARS}"
else
  ok "base_domain already set: ${current}"
fi
