#!/usr/bin/env bash
set -euo pipefail

ENV_NAME="${1:-dev}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_DIR="${ROOT_DIR}/stacks/${ENV_NAME}"
AUTO_TFVARS="${ENV_DIR}/env.auto.tfvars"

ENV_TFVARS_FILE="${ENV_DIR}/env.tfvars"


mkdir -p "${ENV_DIR}"

# Read current base_domain from env.auto.tfvars if exists
current=""
if [[ -f "${AUTO_TFVARS}" ]]; then
  current="$(grep -E '^[[:space:]]*base_domain[[:space:]]*=' "${AUTO_TFVARS}" | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/' | tail -n 1 || true)"
fi

# Fallback: env.tfvars에 실제 값이 있으면 우선 사용
if [[ -z "${current}" && -f "${ENV_TFVARS_FILE}" ]]; then
  tfv="$(grep -E '^[[:space:]]*base_domain[[:space:]]*=' "${ENV_TFVARS_FILE}" | sed -E 's/.*=[[:space:]]*\"([^\"]+)\".*/\1/' | tail -n 1 || true)"
  if [[ -n "${tfv}" ]]; then
    current="${tfv}"
  fi
fi

# Treat empty or placeholder values as "not set"
is_placeholder="false"
case "${current}" in
  ""|"example.com"|"basedomain.net"|"mymeta.net")
    is_placeholder="true"
    ;;
esac

if [[ "${is_placeholder}" == "true" ]]; then
  echo ""
  echo "[env-init] base_domain 이 설정되어 있지 않습니다."
  echo "          예) mycompany.net"
  read -r -p "Enter base_domain: " input
  if [[ -z "${input}" ]]; then
    echo "base_domain is required."
    exit 1
  fi

  cat > "${AUTO_TFVARS}" <<EOF
# Auto-generated by scripts/ensure-base-domain.sh
base_domain = "${input}"
EOF
  echo "[env-init] wrote ${AUTO_TFVARS}"
else
  echo "[env-init] base_domain already set: ${current}"
fi
