# ==============================================================================
# ClusterSecretStore — Vault Backend
#
# ESO가 Vault에서 Secret을 읽어오기 위한 인증 설정
# Vault K8s Auth Method 사용 (ServiceAccount 기반)
#
# 사전 조건:
#   1. Vault K8s Auth Method 활성화: vault auth enable kubernetes
#   2. ESO용 Role 생성: vault write auth/kubernetes/role/external-secrets ...
#   3. platform-read Policy 생성: vault policy write platform-read ...
#   → scripts/credential-init/vault-seed.sh 참조
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: credential-init
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
