# ==============================================================================
# Keycloak Public Ingress
#
# Keycloak EC2 (private subnet)를 K8s nginx ingress를 통해 공개 노출
# AWS IAM OIDC Provider가 OIDC Discovery endpoint에 접근할 수 있도록 구성
#
# Flow: Internet → NLB → nginx-ingress → K8s Service → Keycloak EC2:8080
# ==============================================================================
---
# Headless Service + Manual Endpoints → Keycloak EC2 private IP
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
---
# Manual Endpoints — Keycloak EC2 private IP
apiVersion: v1
kind: Endpoints
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
subsets:
  - addresses:
      - ip: 10.0.101.201
    ports:
      - name: http
        port: 8080
        protocol: TCP
      - name: https
        port: 8443
        protocol: TCP
---
# Public Ingress — cert-manager TLS + nginx class
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Keycloak은 HTTP 8080에서도 서비스 가능 (프록시 모드)
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keycloak.dev.unifiedmeta.net
      secretName: keycloak-tls
  rules:
    - host: keycloak.dev.unifiedmeta.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
