# ==============================================================================
# ExternalSecret — ArgoCD OIDC Client Secret
#
# Vault KV: secret/platform/oidc/argocd → K8s Secret: argocd-oidc-secret
#
# ArgoCD Helm values (argocd-values.yaml.tftpl)에서 참조:
#   clientSecret: $argocd-oidc-secret:oidc.keycloak.clientSecret
#
# ArgoCD는 Secret 이름과 키를 $<secret-name>:<key> 형식으로 참조
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: credential-init
    # ArgoCD가 자체 Secret으로 인식하도록 라벨 추가
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: oidc.keycloak.clientSecret
      remoteRef:
        key: secret/data/platform/oidc/argocd
        property: client-secret
