# ==============================================================================
# ExternalSecret — Grafana OIDC Client Secret
#
# Vault KV: secret/platform/oidc/grafana → K8s Secret: grafana-oidc-secret
#
# Grafana Helm values (monitoring.yaml)에서 참조:
#   envFromSecret: "grafana-oidc-secret"  (추가 envFrom)
#   client_secret: "$__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
#
# Secret key = Grafana 환경변수 이름이어야 함
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: credential-init
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: secret/data/platform/oidc/grafana
        property: client-secret
