# ==============================================================================
# ExternalSecret — Rancher OIDC Client Secret
#
# Vault KV: secret/platform/oidc/rancher → K8s Secret: rancher-oidc-secret
# Rancher Keycloak Auth Provider 설정에서 참조
# ==============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rancher-oidc-secret
  namespace: cattle-system
  labels:
    app.kubernetes.io/part-of: credential-init
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rancher-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: secret/data/platform/oidc/rancher
        property: client-secret
